.TH "colorLen_t" 3 "Sun Mar 19 2017" "Version 1.0.00" "Library Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorLen_t \- Supported colors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libDbg\&.c>\fP
.SH "Detailed Description"
.PP 
Supported colors\&. 

Esta estrutura eh criada via xmacro 
.PP
Definition at line 57 of file libDbg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Library Debug from the source code\&.
