.TH "/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/llogDebug/example/example.c" 3 "Sun Mar 19 2017" "Version 1.0.00" "Library Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/llogDebug/example/example.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'libDbg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgreet\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int greet ()"

.PP
Definition at line 12 of file example\&.c\&.
.SS "int main ()"

.PP
Definition at line 22 of file example\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Library Debug from the source code\&.
