.TH "libDbgDate_t" 3 "Sun Mar 19 2017" "Version 1.0.00" "Library Debug" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libDbgDate_t \- Date variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libDbg\&.c>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fByear\fP"
.br
.ti -1c
.RI "int \fBmon\fP"
.br
.ti -1c
.RI "int \fBday\fP"
.br
.ti -1c
.RI "int \fBhour\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBsec\fP"
.br
.ti -1c
.RI "int \fBusec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Date variables\&. 
.PP
Definition at line 106 of file libDbg\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int day"

.PP
Definition at line 109 of file libDbg\&.c\&.
.SS "int hour"

.PP
Definition at line 110 of file libDbg\&.c\&.
.SS "int min"

.PP
Definition at line 111 of file libDbg\&.c\&.
.SS "int mon"

.PP
Definition at line 108 of file libDbg\&.c\&.
.SS "int sec"

.PP
Definition at line 112 of file libDbg\&.c\&.
.SS "int usec"

.PP
Definition at line 113 of file libDbg\&.c\&.
.SS "int year"

.PP
Definition at line 107 of file libDbg\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Library Debug from the source code\&.
